#Saved values for reminder1
#Wed Apr 15 12:39:25 BST 2026
BODY=Please arrange payment as soon as possible to avoid further action.
END\ MESSAGE=If you have already paid, please disregard this notice.
OPENING\ MESSAGE=Our records show that your payment is now overdue.
SIGNED=peter popov
